/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadsGroupIdRouteImport } from './routes/squads.$groupId'
import { Route as JoinTokenRouteImport } from './routes/join.$token'

const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsGroupIdRoute = SquadsGroupIdRouteImport.update({
  id: '/squads/$groupId',
  path: '/squads/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/squads': typeof SquadsRoute
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/squads': typeof SquadsRoute
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/squads': typeof SquadsRoute
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/focus' | '/friends' | '/memories' | '/squads' | '/join/$token' | '/squads/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/focus' | '/friends' | '/memories' | '/squads' | '/join/$token' | '/squads/$groupId'
  id: '__root__' | '/' | '/focus' | '/friends' | '/memories' | '/squads' | '/join/$token' | '/squads/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusRoute: typeof FocusRoute
  FriendsRoute: typeof FriendsRoute
  MemoriesRoute: typeof MemoriesRoute
  SquadsRoute: typeof SquadsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SquadsGroupIdRoute: typeof SquadsGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$groupId': {
      id: '/squads/$groupId'
      path: '/squads/$groupId'
      fullPath: '/squads/$groupId'
      preLoaderRoute: typeof SquadsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRoute,
  FriendsRoute: FriendsRoute,
  MemoriesRoute: MemoriesRoute,
  SquadsRoute: SquadsRoute,
  JoinTokenRoute: JoinTokenRoute,
  SquadsGroupIdRoute: SquadsGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
