/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadsGroupIdRouteImport } from './routes/squads.$groupId'
import { Route as JoinTokenRouteImport } from './routes/join.$token'

const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsGroupIdRoute = SquadsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => SquadsRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/mentor': typeof MentorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/squads': typeof SquadsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/mentor': typeof MentorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/squads': typeof SquadsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/mentor': typeof MentorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/squads': typeof SquadsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/squads/$groupId': typeof SquadsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/focus'
    | '/friends'
    | '/memories'
    | '/mentor'
    | '/reset-password'
    | '/squads'
    | '/join/$token'
    | '/squads/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/focus'
    | '/friends'
    | '/memories'
    | '/mentor'
    | '/reset-password'
    | '/squads'
    | '/join/$token'
    | '/squads/$groupId'
  id:
    | '__root__'
    | '/'
    | '/focus'
    | '/friends'
    | '/memories'
    | '/mentor'
    | '/reset-password'
    | '/squads'
    | '/join/$token'
    | '/squads/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusRoute: typeof FocusRoute
  FriendsRoute: typeof FriendsRoute
  MemoriesRoute: typeof MemoriesRoute
  MentorRoute: typeof MentorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SquadsRoute: typeof SquadsRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$groupId': {
      id: '/squads/$groupId'
      path: '/$groupId'
      fullPath: '/squads/$groupId'
      preLoaderRoute: typeof SquadsGroupIdRouteImport
      parentRoute: typeof SquadsRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SquadsRouteChildren {
  SquadsGroupIdRoute: typeof SquadsGroupIdRoute
}

const SquadsRouteChildren: SquadsRouteChildren = {
  SquadsGroupIdRoute: SquadsGroupIdRoute,
}

const SquadsRouteWithChildren =
  SquadsRoute._addFileChildren(SquadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRoute,
  FriendsRoute: FriendsRoute,
  MemoriesRoute: MemoriesRoute,
  MentorRoute: MentorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SquadsRoute: SquadsRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
